// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitLog(arg1:string):Promise<void>;

export function GetAppDataDir():Promise<string>;

export function RemoveAmd():Promise<void>;

export function RunCmd(arg1:string):Promise<string>;

export function SetupAmd():Promise<void>;

export function WhichCmd(arg1:string):Promise<string>;
