// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitLog(arg1) {
  return window['go']['app']['App']['EmitLog'](arg1);
}

export function GetAppDataDir() {
  return window['go']['app']['App']['GetAppDataDir']();
}

export function IsAmdRunning() {
  return window['go']['app']['App']['IsAmdRunning']();
}

export function KillAmd() {
  return window['go']['app']['App']['KillAmd']();
}

export function OpenAppDataDir() {
  return window['go']['app']['App']['OpenAppDataDir']();
}

export function RemoveAmd() {
  return window['go']['app']['App']['RemoveAmd']();
}

export function RunCmd(arg1) {
  return window['go']['app']['App']['RunCmd'](arg1);
}

export function SendInput(arg1) {
  return window['go']['app']['App']['SendInput'](arg1);
}

export function SetupAmd() {
  return window['go']['app']['App']['SetupAmd']();
}

export function StartAmd() {
  return window['go']['app']['App']['StartAmd']();
}

export function StopAmd() {
  return window['go']['app']['App']['StopAmd']();
}

export function WhichCmd(arg1) {
  return window['go']['app']['App']['WhichCmd'](arg1);
}
